### ISSUE TITLE
RuntimeError: entity expansion has grown too large

### ISSUE THREAD

**Issue by jogaco** [bjjb/ebayr#17]
I get this error for an item with a description with many html entities.

 ```
	from /home/my/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rexml/text.rb:398:in `block in unnormalize'
	from /home/my/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rexml/text.rb:395:in `gsub'
	from /home/my/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rexml/text.rb:395:in `unnormalize'
	from /home/my/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rexml/text.rb:252:in `value'
	from /home/my/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rexml/element.rb:452:in `text'
	from /home/my/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rexml/element.rb:433:in `has_text?'
	from /home/my/.rvm/gems/ruby-2.1.3@project/gems/activesupport-4.2.0/lib/active_support/xml_mini/rexml.rb:74:in `merge_texts!'
	from /home/my/.rvm/gems/ruby-2.1.3@project/gems/activesupport-4.2.0/lib/active_support/xml_mini/rexml.rb:63:in `collapse'
	from /home/my/.rvm/gems/ruby-2.1.3@project/gems/activesupport-4.2.0/lib/active_support/xml_mini/rexml.rb:48:in `merge_element!'
	from /home/my/.rvm/gems/ruby-2.1.3@project/gems/activesupport-4.2.0/lib/active_support/xml_mini/rexml.rb:59:in `block in collapse'
	from /home/my/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rexml/element.rb:902:in `block in each'
	from /home/my/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rexml/xpath.rb:67:in `each'
	from /home/my/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rexml/xpath.rb:67:in `each'
	from /home/my/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rexml/element.rb:902:in `each'
	from /home/my/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rexml/element.rb:393:in `each_element'
	from /home/my/.rvm/gems/ruby-2.1.3@project/gems/activesupport-4.2.0/lib/active_support/xml_mini/rexml.rb:59:in `collapse'
... 14 levels...
	from /home/my/.rvm/gems/ruby-2.1.3@project/gems/ebayr-0.0.9/lib/ebayr/response.rb:10:in `initialize'
	from /home/my/.rvm/gems/ruby-2.1.3@project/gems/ebayr-0.0.9/lib/ebayr/request.rb:86:in `new'
	from /home/my/.rvm/gems/ruby-2.1.3@project/gems/ebayr-0.0.9/lib/ebayr/request.rb:86:in `send'
 ```

**Comment by bjjb** [comment]
Fixed by #20
